import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { api, type VocabularyInboxItem } from "../api/client";
const text={aria:"Ghi nhanh t\u1eeb m\u1edbi",close:"\u0110\u00f3ng",term:"T\u1eeb ho\u1eb7c c\u1ee5m t\u1eeb",termPlaceholder:"V\u00ed d\u1ee5: negotiate",context:"Ng\u1eef c\u1ea3nh",contextPlaceholder:"B\u1ea1n g\u1eb7p t\u1eeb n\u00e0y \u1edf \u0111\u00e2u ho\u1eb7c mu\u1ed1n d\u00f9ng th\u1ebf n\u00e0o?",error:"Kh\u00f4ng th\u1ec3 l\u01b0u ghi ch\u00fa",note:"AI t\u1ea1o ngh\u0129a, IPA, ba v\u00ed d\u1ee5 v\u00e0 \u0111\u1ec1 xu\u1ea5t mindmap. B\u1ea1n duy\u1ec7t tr\u01b0\u1edbc khi l\u01b0u v\u00e0o b\u00e0i h\u1ecdc.",loading:"\u0110ang ph\u00e2n t\u00edch\u2026",submit:"L\u01b0u v\u00e0 nh\u1edd AI ph\u00e2n t\u00edch"};
export function QuickCaptureDrawer({open,onClose,onCreated,hints}:{open:boolean;onClose:()=>void;onCreated?:(item:VocabularyInboxItem)=>void;hints?:{mindmapId?:number;parentNodeId?:number}|null}){
  const [rawText,setRawText]=useState("");const [contextText,setContextText]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!open){setRawText("");setContextText("");setError("")}},[open]);if(!open)return null;
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!rawText.trim())return;setLoading(true);setError("");try{const item=await api.captureVocabulary({rawText,contextText,sourceType:hints?.mindmapId?"mindmap":"quick_capture",sourceReference:hints?.mindmapId?`map:${hints.mindmapId}`:"",hintMindmapId:hints?.mindmapId,hintParentNodeId:hints?.parentNodeId});onCreated?.(item);setRawText("");setContextText("");onClose()}catch(reason){setError(reason instanceof Error?reason.message:text.error)}finally{setLoading(false)}};
  return <aside className="quick-capture-drawer" aria-label={text.aria}><header><div><small>VOCABULARY INBOX</small><h2>Ghi nhanh</h2></div><button onClick={onClose} aria-label={text.close}><X size={18}/></button></header><form onSubmit={submit}><label>{text.term}<input autoFocus value={rawText} onChange={event=>setRawText(event.target.value)} placeholder={text.termPlaceholder} maxLength={500}/></label><label>{text.context}<textarea value={contextText} onChange={event=>setContextText(event.target.value)} placeholder={text.contextPlaceholder} maxLength={1000}/></label>{error&&<p className="capture-error">{error}</p>}<p className="capture-note">{text.note}</p><button className="capture-submit" disabled={loading||!rawText.trim()}>{loading?text.loading:text.submit}</button></form></aside>;
}
