import { afterEach,beforeEach,describe,expect,it } from "vitest";
import fs from "node:fs";import os from "node:os";import path from "node:path";
import type { AppDatabase } from "../../src/server/db/database";import {createDatabase} from "../../src/server/db/database";import{migrate}from"../../src/server/db/migrate";import{ContentRepository}from"../../src/server/modules/content/repository";import{LearningRepository}from"../../src/server/modules/learning/repository";import{SpeakingRepository}from"../../src/server/modules/speaking/repository";import{DocumentRepository}from"../../src/server/modules/documents/repository";
let db:AppDatabase;let root:string;beforeEach(()=>{db=createDatabase(":memory:");migrate(db);db.prepare("INSERT INTO users(username,normalized_username,password_hash) VALUES (?,?,?)").run("one","one","hash");db.prepare("INSERT INTO users(username,normalized_username,password_hash) VALUES (?,?,?)").run("two","two","hash");root=fs.mkdtempSync(path.join(os.tmpdir(),"mme-user-"))});afterEach(()=>{db.close();fs.rmSync(root,{recursive:true,force:true})});
const draft={topicId:1,title:"Private map",description:"",source:"user" as const,nodes:[{parentIndex:null,nodeType:"root" as const,label:"Private",meaningVi:"",ipa:"",color:"coral" as const,x:0,y:0,cefr:"A2" as const}]};

describe("user data isolation",()=>{
 it("isolates mindmaps and learning sessions",()=>{db.prepare("INSERT INTO topics(slug,title,title_vi) VALUES ('t','T','T')").run();const content=new ContentRepository(db);const map=content.saveMindmapDraft(draft,1);expect(content.getMindmap(map.id,2)).toBeNull();expect(content.getMindmap(map.id,1)).not.toBeNull();const learning=new LearningRepository(db);const session=learning.createSession(10,1) as {id:number};expect(learning.getSession(session.id,2)).toBeNull();expect(learning.getSession(session.id,1)).not.toBeNull()});
 it("isolates notebook and documents",()=>{const speaking=new SpeakingRepository(db);const note=speaking.addSentence({sentence:"Private sentence",sourceType:"user"},1) as {id:number};expect(speaking.listNotebook(2)).toEqual([]);expect(speaking.listNotebook(1)).toHaveLength(1);const documents=new DocumentRepository(db,{dataDir:root} as never);const doc=documents.create({title:"Private",originalFilename:"a.txt",format:"txt",mimeType:"text/plain",buffer:Buffer.from("hello")},1) as unknown as {id:number};expect(documents.get(doc.id,2)).toBeNull();expect(documents.get(doc.id,1)).not.toBeNull();const section=(documents.get(doc.id,1) as {sections:Array<{id:number}>}).sections[0];expect(documents.addVocabulary(doc.id,{sectionId:section.id,selectedText:"hello",startOffset:0,endOffset:5,meaningVi:"xin chào"},2)).toBeNull();expect(note.id).toBeGreaterThan(0)});
});
