// @vitest-environment jsdom
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AgentDrawer } from "../../src/client/components/AgentDrawer";
import { api } from "../../src/client/api/client";
import { AppStoreProvider } from "../../src/client/state/app-store";

vi.mock("../../src/client/api/client", async (importOriginal) => { const original=await importOriginal<typeof import("../../src/client/api/client")>();return{...original,api:{...original.api,agentStatus:vi.fn(),agentThreads:vi.fn(),createAgentThread:vi.fn(),agentMessages:vi.fn(),sendAgentMessage:vi.fn(),retryAgentMessage:vi.fn(),archiveAgentThread:vi.fn(),restoreAgentThread:vi.fn(),renameAgentThread:vi.fn(),deleteAgentThread:vi.fn(),saveAgentVocabularyNote:vi.fn(),mindmaps:vi.fn(),generateMindmapExtension:vi.fn(),saveMindmapExtension:vi.fn()}}});
afterEach(cleanup);
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.agentStatus).mockResolvedValue({skill:"mindmap-english-tutor",skillVersion:"1.0.0",degraded:false});vi.mocked(api.agentThreads).mockResolvedValue([{id:4,title:"Present perfect",preview:"Dùng khi...",updatedAt:"2026-07-14"}]);vi.mocked(api.agentMessages).mockResolvedValue([{id:1,threadId:4,role:"assistant",content:"Chào bạn",status:"completed",cacheHit:0}]);vi.mocked(api.archiveAgentThread).mockResolvedValue();vi.mocked(api.restoreAgentThread).mockResolvedValue();vi.mocked(api.renameAgentThread).mockResolvedValue();vi.mocked(api.mindmaps).mockResolvedValue([{id:17,title:"Daily Routine",topicId:1,description:"",status:"approved",source:"seed",topicTitleVi:"Đời sống",nodeCount:12}]);});

describe("AgentDrawer",()=>{
  it("scrolls to the newest message after a long chat updates",async()=>{const scrollIntoView=vi.fn();Object.defineProperty(HTMLElement.prototype,"scrollIntoView",{configurable:true,value:scrollIntoView});vi.mocked(api.agentMessages).mockResolvedValueOnce(Array.from({length:20},(_,index)=>({id:index+1,threadId:4,role:index%2===0?"assistant" as const:"user" as const,content:`Message ${index+1}`,status:"completed" as const,cacheHit:0})));render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);expect(await screen.findByText("Message 20")).toBeInTheDocument();expect(scrollIntoView).toHaveBeenCalledWith({block:"end"});});
  it("restores history and creates a new chat",async()=>{vi.mocked(api.createAgentThread).mockResolvedValue({id:5,title:"",updatedAt:"2026-07-14"});render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);expect(await screen.findByText("Present perfect")).toBeInTheDocument();expect(await screen.findByText("Chào bạn")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Chat mới"}));expect(api.createAgentThread).toHaveBeenCalledOnce();});
  it("reloads persisted provider errors and retries same message",async()=>{const failed={id:8,threadId:4,role:"assistant" as const,content:"Model unavailable",status:"failed",cacheHit:0};vi.mocked(api.agentMessages).mockResolvedValueOnce([{id:1,threadId:4,role:"assistant",content:"Chào bạn",status:"completed",cacheHit:0}]).mockResolvedValueOnce([{id:7,threadId:4,role:"user",content:"alo",status:"completed",cacheHit:0},failed]);vi.mocked(api.sendAgentMessage).mockRejectedValue(new Error("Model unavailable"));vi.mocked(api.retryAgentMessage).mockResolvedValue({reply:"Đã hoạt động",message:{...failed,content:"Đã hoạt động",status:"completed"},suggestions:[]});render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("Chào bạn");await user.type(screen.getByPlaceholderText("Hỏi, sửa câu hoặc luyện hội thoại…"),"alo");await user.click(screen.getByRole("button",{name:"Gửi"}));expect(await screen.findByText("Model unavailable")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Thử lại"}));expect(await screen.findByText("Đã hoạt động")).toBeInTheDocument();expect(api.retryAgentMessage).toHaveBeenCalledWith(4,8);});
  it("opens archive and restores a thread",async()=>{vi.mocked(api.agentThreads).mockImplementation(async(archived=false)=>archived?[{id:9,title:"Archived chat",updatedAt:"2026-07-14",archivedAt:"2026-07-14"}]:[{id:4,title:"Present perfect",updatedAt:"2026-07-14"}]);render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("Present perfect");await user.click(screen.getByText("Lưu trữ",{selector:"button"}));expect(await screen.findByText("Archived chat")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Khôi phục"}));expect(api.restoreAgentThread).toHaveBeenCalledWith(9);});
  it("saves a user message to the vocabulary inbox",async()=>{vi.mocked(api.agentMessages).mockResolvedValue([{id:3,threadId:4,role:"user",content:"negotiate",status:"completed",cacheHit:0}]);vi.mocked(api.saveAgentVocabularyNote).mockResolvedValue({id:11,status:"ready",rawText:"negotiate"} as never);render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("negotiate");await user.click(screen.getByRole("button",{name:"L\u01b0u v\u00e0o h\u1ed9p t\u1eeb m\u1edbi"}));expect(api.saveAgentVocabularyNote).toHaveBeenCalledWith(expect.objectContaining({rawText:"negotiate",sourceType:"agent_chat"}));});
  it("turns an update mindmap request into a draft card and approves it",async()=>{const draft={mindmapTitle:"Daily Routine",branches:[{parentLabel:"Morning",meaningVi:"buổi sáng",color:"amber" as const,words:[{term:"make the bed",meaningVi:"dọn giường",ipa:"",cefr:"A2" as const,example:"I make the bed.",exampleVi:"Tôi dọn giường."}]}]};vi.mocked(api.createAgentThread).mockResolvedValue({id:5,title:"",updatedAt:"2026-07-14"});vi.mocked(api.generateMindmapExtension).mockResolvedValue({jobId:99,draft,duplicates:[]});vi.mocked(api.saveMindmapExtension).mockResolvedValue({id:17,topicId:1,title:"Daily Routine",description:"",status:"approved",source:"seed",nodes:[]} as never);render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("Chào bạn");await user.type(screen.getByPlaceholderText("Hỏi, sửa câu hoặc luyện hội thoại…"),"thêm 10 từ vào Daily Routine");await user.click(screen.getByRole("button",{name:"Gửi"}));expect(await screen.findByText("Bản nháp thêm từ đã sẵn sàng")).toBeInTheDocument();expect(screen.getByText("make the bed")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Duyệt thêm vào mindmap"}));expect(api.saveMindmapExtension).toHaveBeenCalledWith(17,draft);expect(await screen.findByText("Đã thêm vào Daily Routine"));});
});
