// @vitest-environment jsdom
import { cleanup, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AgentDrawer } from "../../src/client/components/AgentDrawer";
import { api } from "../../src/client/api/client";
import { AppStoreProvider } from "../../src/client/state/app-store";

vi.mock("../../src/client/api/client", async (importOriginal) => { const original=await importOriginal<typeof import("../../src/client/api/client")>();return{...original,api:{...original.api,agentStatus:vi.fn(),agentThreads:vi.fn(),createAgentThread:vi.fn(),agentMessages:vi.fn(),sendAgentMessage:vi.fn(),retryAgentMessage:vi.fn(),archiveAgentThread:vi.fn(),restoreAgentThread:vi.fn(),renameAgentThread:vi.fn(),deleteAgentThread:vi.fn()}}});
afterEach(cleanup);
beforeEach(()=>{vi.clearAllMocks();vi.mocked(api.agentStatus).mockResolvedValue({skill:"mindmap-english-tutor",skillVersion:"1.0.0",degraded:false});vi.mocked(api.agentThreads).mockResolvedValue([{id:4,title:"Present perfect",preview:"Dùng khi...",updatedAt:"2026-07-14"}]);vi.mocked(api.agentMessages).mockResolvedValue([{id:1,threadId:4,role:"assistant",content:"Chào bạn",status:"completed",cacheHit:0}]);vi.mocked(api.archiveAgentThread).mockResolvedValue();vi.mocked(api.restoreAgentThread).mockResolvedValue();vi.mocked(api.renameAgentThread).mockResolvedValue();});

describe("AgentDrawer",()=>{
  it("restores history and creates a new chat",async()=>{vi.mocked(api.createAgentThread).mockResolvedValue({id:5,title:"",updatedAt:"2026-07-14"});render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);expect(await screen.findByText("Present perfect")).toBeInTheDocument();expect(await screen.findByText("Chào bạn")).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Chat mới"}));expect(api.createAgentThread).toHaveBeenCalledOnce();});
  it("reloads persisted provider errors and retries same message",async()=>{const failed={id:8,threadId:4,role:"assistant" as const,content:"Model unavailable",status:"failed",cacheHit:0};vi.mocked(api.agentMessages).mockResolvedValueOnce([{id:1,threadId:4,role:"assistant",content:"Chào bạn",status:"completed",cacheHit:0}]).mockResolvedValueOnce([{id:7,threadId:4,role:"user",content:"alo",status:"completed",cacheHit:0},failed]);vi.mocked(api.sendAgentMessage).mockRejectedValue(new Error("Model unavailable"));vi.mocked(api.retryAgentMessage).mockResolvedValue({reply:"Đã hoạt động",message:{...failed,content:"Đã hoạt động",status:"completed"},suggestions:[]});render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("Chào bạn");await user.type(screen.getByPlaceholderText("Hỏi, sửa câu hoặc luyện hội thoại…"),"alo");await user.click(screen.getByRole("button",{name:"Gửi"}));expect(await screen.findByText("Model unavailable")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Thử lại"}));expect(await screen.findByText("Đã hoạt động")).toBeInTheDocument();expect(api.retryAgentMessage).toHaveBeenCalledWith(4,8);});
  it("opens archive and restores a thread",async()=>{vi.mocked(api.agentThreads).mockImplementation(async(archived=false)=>archived?[{id:9,title:"Archived chat",updatedAt:"2026-07-14",archivedAt:"2026-07-14"}]:[{id:4,title:"Present perfect",updatedAt:"2026-07-14"}]);render(<AppStoreProvider><AgentDrawer/></AppStoreProvider>);const user=userEvent.setup();await screen.findByText("Present perfect");await user.click(screen.getByText("Lưu trữ",{selector:"button"}));expect(await screen.findByText("Archived chat")).toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Khôi phục"}));expect(api.restoreAgentThread).toHaveBeenCalledWith(9);});
});
