import type {LearningItem} from "../api/client";
export interface LearningPromptModel{expectedLanguage:"en"|"vi"|"speak";frontPrimary:string;frontSecondary:string;question:string;placeholder:string;hintLabel:string;answer:string;hintSource:string}
export function createLearningPrompt(item:LearningItem):LearningPromptModel{
 if(item.activityType==="meaning-recall")return{expectedLanguage:"en",frontPrimary:item.meaningVi,frontSecondary:"Nhớ lại từ tiếng Anh",question:"Từ tiếng Anh phù hợp là gì?",placeholder:"Nhập từ hoặc cụm từ tiếng Anh...",hintLabel:"Gợi ý tiếng Anh",answer:item.term,hintSource:item.term};
 if(item.activityType==="context")return{expectedLanguage:"vi",frontPrimary:(item.example||item.term).replace(new RegExp(escapeRegExp(item.term),"ig"),"_____"),frontSecondary:"Giải thích ngữ cảnh bằng tiếng Việt",question:"Giải thích nghĩa hoặc đặt câu bằng tiếng Việt.",placeholder:"Nhập nghĩa hoặc câu tiếng Việt...",hintLabel:"Gợi ý tiếng Việt",answer:item.meaningVi,hintSource:item.meaningVi};
 if(item.activityType==="speak")return{expectedLanguage:"speak",frontPrimary:item.example||item.term,frontSecondary:"Đọc thành tiếng",question:"Nghe và nói lại câu tiếng Anh.",placeholder:"",hintLabel:"Gợi ý phát âm",answer:item.term,hintSource:item.ipa||item.term};
 return{expectedLanguage:"vi",frontPrimary:item.term,frontSecondary:"Nhớ lại nghĩa tiếng Việt",question:"Bạn nhớ nghĩa tiếng Việt của từ này không?",placeholder:"Nhập nghĩa hoặc câu tiếng Việt...",hintLabel:"Gợi ý tiếng Việt",answer:item.meaningVi,hintSource:item.meaningVi};
}
export function getLearningHint(model:LearningPromptModel,level:number){const source=model.hintSource.trim();if(!source)return"Chưa có gợi ý.";if(model.expectedLanguage==="speak")return source;const visible=Math.min(source.length,Math.max(1,level+1));return `${source.slice(0,visible)}${"•".repeat(Math.max(1,Math.min(8,source.length-visible)))}`}
export function isLearningAnswerCorrect(model:LearningPromptModel,answer:string){const normalizedAnswer=normalizeAnswer(answer,model.expectedLanguage);if(!normalizedAnswer)return false;return answerVariants(model.answer,model.expectedLanguage).some(expected=>normalizedAnswer===expected)}
function answerVariants(answer:string,language:LearningPromptModel["expectedLanguage"]){const variants=new Set<string>();for(const part of answer.split(/[;,/|]+/)){const normalized=normalizeAnswer(part,language);if(normalized)variants.add(normalized)}const whole=normalizeAnswer(answer,language);if(whole)variants.add(whole);return [...variants]}
function normalizeAnswer(value:string,language:LearningPromptModel["expectedLanguage"]){let normalized=value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("vi").replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();if(language==="en")normalized=normalized.replace(/^(a|an|the)\s+/,"");return normalized}
function escapeRegExp(value:string){return value.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}