import { useState, type FormEvent } from "react";
import { Copy, Download, Sparkles } from "lucide-react";
import { useAuth } from "../auth/auth-context";

export function AuthPage(){
  const auth=useAuth();
  const [mode,setMode]=useState<"login"|"register"|"recover">("login");
  const [username,setUsername]=useState("");const[password,setPassword]=useState("");const[confirmation,setConfirmation]=useState("");const[recoveryCode,setRecoveryCode]=useState("");const[error,setError]=useState("");const[saved,setSaved]=useState(false);const[busy,setBusy]=useState(false);
  if(auth.status==="loading")return <div className="auth-loading"><span className="loader"/>Đang mở không gian học…</div>;
  if(auth.status==="recovery-checkpoint"){
    const download=()=>{const blob=new Blob([`MindMap English recovery code\n${auth.recoveryCode}\n`],{type:"text/plain"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="mindmap-english-recovery-code.txt";link.click();URL.revokeObjectURL(url)};
    return <main className="recovery-screen"><section><p className="eyebrow">BƯỚC QUAN TRỌNG</p><h1>Lưu chìa khóa<br/><em>khôi phục.</em></h1><p>Code chỉ hiện lần này. Dùng khi quên mật khẩu.</p><code>{auth.recoveryCode}</code><div className="recovery-actions"><button onClick={()=>void navigator.clipboard?.writeText(auth.recoveryCode)}><Copy size={17}/>Sao chép</button><button onClick={download}><Download size={17}/>Tải xuống</button></div><label><input type="checkbox" checked={saved} onChange={event=>setSaved(event.target.checked)}/> Tôi đã lưu recovery code</label><button className="auth-primary" disabled={!saved} onClick={auth.confirmRecoverySaved}>Tiếp tục vào app</button></section></main>;
  }
  const submit=async(event:FormEvent)=>{event.preventDefault();setError("");setBusy(true);try{if(mode==="login")await auth.login({username,password});else if(mode==="register")await auth.register({username,password,passwordConfirmation:confirmation});else await auth.recover({username,recoveryCode,password,passwordConfirmation:confirmation})}catch(value){setError(value instanceof Error?value.message:"Không thể xác thực")}finally{setBusy(false)}};
  return <main className="auth-page"><section className="auth-story"><div className="auth-brand"><span><Sparkles size={20}/></span>MindMap <b>English</b></div><div><p className="eyebrow">LOCAL-FIRST · RIÊNG THEO ACCOUNT</p><h1>Học ít hơn.<br/><em>Nhớ đúng hơn.</em></h1><p>Mindmap, sách, luyện nói và Gia sư AI tiếp tục đúng nơi bạn dừng lại.</p></div></section><section className="auth-panel"><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Đăng nhập</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Tạo tài khoản</button></div><form onSubmit={submit}><h2>{mode==="login"?"Chào bạn quay lại.":mode==="register"?"Tạo không gian học.":"Khôi phục tài khoản."}</h2><p>{mode==="login"?"Tiếp tục bài học, tiến độ và lịch sử chat gần nhất.":mode==="register"?"Chỉ cần username và mật khẩu.":"Nhập recovery code đã lưu."}</p><label>Tên đăng nhập<input aria-label="Tên đăng nhập" value={username} onChange={event=>setUsername(event.target.value)} autoComplete="username"/></label>{mode==="recover"&&<label>Recovery code<input aria-label="Recovery code" value={recoveryCode} onChange={event=>setRecoveryCode(event.target.value)} /></label>}<label>Mật khẩu<input aria-label="Mật khẩu" type="password" value={password} onChange={event=>setPassword(event.target.value)} autoComplete={mode==="login"?"current-password":"new-password"}/></label>{mode!=="login"&&<label>Xác nhận mật khẩu<input aria-label="Xác nhận mật khẩu" type="password" value={confirmation} onChange={event=>setConfirmation(event.target.value)}/></label>}{error&&<div className="notice error">{error}</div>}<button className="auth-primary" disabled={busy}>{mode==="login"?"Vào không gian học":mode==="register"?"Tạo không gian học":"Đặt mật khẩu mới"}</button>{mode==="login"&&<button type="button" className="auth-link" onClick={()=>setMode("recover")}>Quên mật khẩu?</button>}</form></section></main>;
}
