import { useEffect, useState } from "react";
import { Check, RefreshCw, Trash2 } from "lucide-react";
import { api, type VocabularyEnrichmentDraft, type VocabularyInboxItem, type VocabularyInboxStatus } from "../api/client";
const t={ready:"Ch\u1edd duy\u1ec7t",processing:"\u0110ang x\u1eed l\u00fd",failed:"L\u1ed7i",approved:"\u0110\u00e3 l\u01b0u",dismissed:"B\u1ecf qua",title:"H\u1ed9p t\u1eeb m\u1edbi",intro:"AI chu\u1ea9n b\u1ecb. B\u1ea1n quy\u1ebft \u0111\u1ecbnh \u0111i\u1ec1u g\u00ec \u0111\u01b0\u1ee3c \u0111\u01b0a v\u00e0o mindmap v\u00e0 \u00f4n t\u1eadp.",empty:"Ch\u01b0a c\u00f3 ghi ch\u00fa trong m\u1ee5c n\u00e0y.",choose:"Ch\u1ecdn m\u1ed9t ghi ch\u00fa \u0111\u1ec3 xem.",waiting:"\u0110ang ch\u1edd AI ph\u00e2n t\u00edch",original:"GHI CH\u00da G\u1ed0C",term:"T\u1eeb chu\u1ea9n",meaning:"Ngh\u0129a ti\u1ebfng Vi\u1ec7t",uses:"Ba c\u00e1ch d\u00f9ng",example:"V\u00ed d\u1ee5",translation:"D\u1ecbch v\u00ed d\u1ee5",placement:"MINDMAP \u0110\u1ec0 XU\u1ea4T",dismiss:"B\u1ecf qua",approve:"Duy\u1ec7t v\u00e0 \u0111\u01b0a v\u00e0o \u00f4n t\u1eadp",noDraft:"AI ch\u01b0a t\u1ea1o \u0111\u01b0\u1ee3c b\u1ea3n nh\u00e1p.",retry:"Th\u1eed AI l\u1ea1i"};
const tabs:Array<{status:VocabularyInboxStatus;label:string}>=[{status:"ready",label:t.ready},{status:"processing",label:t.processing},{status:"failed",label:t.failed},{status:"approved",label:t.approved},{status:"dismissed",label:t.dismissed}];
export function VocabularyInboxPage({initialStatus="ready"}:{initialStatus?:VocabularyInboxStatus}){
  const [status,setStatus]=useState<VocabularyInboxStatus>(initialStatus);const [items,setItems]=useState<VocabularyInboxItem[]>([]);const [selected,setSelected]=useState<VocabularyInboxItem|null>(null);const [draft,setDraft]=useState<VocabularyEnrichmentDraft|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>setStatus(initialStatus),[initialStatus]);
  const load=async(next=status)=>{const values=await api.vocabularyInbox(next);setItems(values);setSelected(values[0]??null);setDraft(values[0]?.draft??null)};useEffect(()=>{void load()},[status]);
  const choose=(item:VocabularyInboxItem)=>{setSelected(item);setDraft(item.draft)};const approve=async()=>{if(!selected||!draft)return;setBusy(true);try{await api.updateVocabularyDraft(selected.id,draft);await api.approveVocabulary(selected.id,{});await load()}finally{setBusy(false)}};const retry=async()=>{if(!selected)return;setBusy(true);try{const item=await api.retryVocabularyEnrichment(selected.id);if(item.status==="ready"){setStatus("ready")}else{setSelected(item);setDraft(item.draft);await load(status)}}finally{setBusy(false)}};const dismiss=async()=>{if(!selected)return;await api.dismissVocabulary(selected.id);await load()};
  return <div className="page vocabulary-inbox-page"><header className="page-header"><div><p className="eyebrow">PERSONAL WORDS</p><h1>{t.title}</h1><p>{t.intro}</p></div></header><div className="inbox-tabs">{tabs.map(tab=><button key={tab.status} className={status===tab.status?"active":""} onClick={()=>setStatus(tab.status)}>{tab.label}</button>)}</div><div className="inbox-layout"><section className="inbox-list">{items.length===0&&<div className="inbox-empty">{t.empty}</div>}{items.map(item=><button key={item.id} className={selected?.id===item.id?"active":""} onClick={()=>choose(item)}><small>{item.sourceType.replace("_"," ")}</small><b>{item.draft?.displayTerm||item.rawText}</b><span>{item.draft?.meaningVi||item.errorMessage||t.waiting}</span></button>)}</section><section className="inbox-review">{!selected&&<div className="inbox-empty">{t.choose}</div>}{selected&&draft&&<><div className="review-source"><small>{t.original}</small><b>{selected.rawText}</b><span>{selected.contextText}</span></div><div className="review-fields"><label>{t.term}<input value={draft.displayTerm} onChange={event=>setDraft({...draft,displayTerm:event.target.value})}/></label><label>{t.meaning}<input value={draft.meaningVi} onChange={event=>setDraft({...draft,meaningVi:event.target.value})}/></label><label>IPA<input value={draft.ipa} onChange={event=>setDraft({...draft,ipa:event.target.value})}/></label><label>CEFR<select value={draft.cefr} onChange={event=>setDraft({...draft,cefr:event.target.value as VocabularyEnrichmentDraft["cefr"]})}>{["A1","A2","B1","B2"].map(level=><option key={level}>{level}</option>)}</select></label></div><h3>{t.uses}</h3><div className="example-stack">{draft.examples.map((example,index)=><article data-testid="example-card" key={example.role}><small>{example.role.replace("_"," ")}</small><input aria-label={`${t.example} ${index+1}`} value={example.sentence} onChange={event=>setDraft({...draft,examples:draft.examples.map((value,itemIndex)=>itemIndex===index?{...value,sentence:event.target.value}:value)})}/><input aria-label={`${t.translation} ${index+1}`} value={example.translationVi} onChange={event=>setDraft({...draft,examples:draft.examples.map((value,itemIndex)=>itemIndex===index?{...value,translationVi:event.target.value}:value)})}/></article>)}</div><div className="placement-card"><small>{t.placement}</small><b>{draft.placement.newMindmap?.title||`Mindmap #${draft.placement.mindmapId}`}</b><span>{draft.placement.reason||draft.placement.newMindmap?.branchLabel}</span></div><div className="review-actions"><button className="dismiss" onClick={()=>void dismiss()}><Trash2 size={16}/>{t.dismiss}</button><button className="approve" disabled={busy} onClick={()=>void approve()}><Check size={16}/>{t.approve}</button></div></>}{selected&&!draft&&<div className="failed-review"><p>{selected.errorMessage||t.noDraft}</p><button onClick={()=>void retry()} disabled={busy}><RefreshCw size={16}/>{t.retry}</button></div>}</section></div></div>;
}
