import type { AppDatabase } from "../../db/database";

export type ChatRole="user"|"assistant"|"tool";
export class ChatRepository{
  constructor(private readonly db:AppDatabase){}
  createThread(userId:number,title=""){const id=Number(this.db.prepare("INSERT INTO agent_threads(user_id,purpose,title) VALUES (?,'tutor',?)").run(userId,title).lastInsertRowid);return this.getThread(userId,id)!}
  getThread(userId:number,id:number){return this.db.prepare(`SELECT id,title,purpose,created_at createdAt,updated_at updatedAt,archived_at archivedAt FROM agent_threads WHERE id=? AND user_id=?`).get(id,userId) as {id:number;title:string;purpose:string;createdAt:string;updatedAt:string;archivedAt:string|null}|undefined}
  listThreads(userId:number,includeArchived=false){return this.db.prepare(`SELECT t.id,t.title,t.purpose,t.created_at createdAt,t.updated_at updatedAt,t.archived_at archivedAt,(SELECT content FROM agent_messages m WHERE m.thread_id=t.id ORDER BY m.id DESC LIMIT 1) preview FROM agent_threads t WHERE t.user_id=? ${includeArchived?"":"AND t.archived_at IS NULL"} ORDER BY t.updated_at DESC,t.id DESC`).all(userId)}
  listMessages(userId:number,threadId:number){if(!this.getThread(userId,threadId))return null;return this.db.prepare(`SELECT id,thread_id threadId,role,content,status,model,cache_hit cacheHit,skill_version skillVersion,profile_revision profileRevision,created_at createdAt FROM agent_messages WHERE thread_id=? ORDER BY id`).all(threadId)}
  addMessage(userId:number,threadId:number,role:ChatRole,content:string,metadata:{status?:string;model?:string;cacheHit?:boolean;skillVersion?:string;profileRevision?:number}={}){const thread=this.getThread(userId,threadId);if(!thread)return null;const id=Number(this.db.prepare(`INSERT INTO agent_messages(thread_id,role,content,status,model,cache_hit,skill_version,profile_revision) VALUES (?,?,?,?,?,?,?,?)`).run(threadId,role,content,metadata.status??"completed",metadata.model??"",metadata.cacheHit?1:0,metadata.skillVersion??"",metadata.profileRevision??null).lastInsertRowid);if(!thread.title&&role==="user")this.db.prepare("UPDATE agent_threads SET title=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(deriveTitle(content),threadId,userId);else this.db.prepare("UPDATE agent_threads SET updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(threadId,userId);return this.db.prepare("SELECT id,thread_id threadId,role,content,status,created_at createdAt FROM agent_messages WHERE id=?").get(id)}
  archiveThread(userId:number,id:number){return Boolean(this.db.prepare("UPDATE agent_threads SET archived_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND archived_at IS NULL").run(id,userId).changes)}
  renameThread(userId:number,id:number,title:string){return Boolean(this.db.prepare("UPDATE agent_threads SET title=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(title.trim().slice(0,80),id,userId).changes)}
  deleteThread(userId:number,id:number){return Boolean(this.db.prepare("DELETE FROM agent_threads WHERE id=? AND user_id=?").run(id,userId).changes)}
}
function deriveTitle(content:string){const compact=content.replace(/\s+/g," ").trim();return compact.length>48?`${compact.slice(0,47)}…`:compact}
